; ****************
; PyAero Settings
; ****************

[Paths]
DATA_DIR = data
AIRFOILS = ${DATA_DIR}/Airfoils
OUTPUT = ${DATA_DIR}/OUTPUT
LOGS = ${DATA_DIR}/LOGS

[Application]
EXIT_ON_ESCAPE = True
DEFAULT_AIRFOIL = ${Paths:AIRFOILS}/F1K/hn1033a.dat
DECIMAL_SEPARATOR = .

[Window]
WINDOW_STARTUP_MODE = maximized
WINDOW_PRESET_1 = 120, 80, 1800, 1200
WINDOW_PRESET_2 = 140, 90, 1600, 1000
WINDOW_PRESET_3 = 160, 100, 2200, 1400

[Graphics]
MARKER_SIZE = 3
ZOOM_ANCHOR = mouse
VIEW_STYLE = solid
MIN_ZOOM = 10.0
MAX_ZOOM = 120000.0
RUBBERBAND_MIN = 0.08
SCALE_INCREMENT = 1.1
ZOOM_DIRECTION = -1

[Magnifier]
MAGNIFIER_SIZE = 360
MAGNIFIER_MAGNIFICATION = 2.0
MAGNIFIER_OUTLINE_WIDTH = 2.0

[Dialogs]
DIALOG_FILTER = Airfoil contour files (*.dat *.txt)
FILE_FILTER = *.dat, *.txt

[Logging]
LOGCOLOR = rgb(255, 0, 255)
