Subenu :guilabel:`Print preview`
"""""""""""""""""""""""""""""""

The :menuselection:`File --> Print preview` submenu allows previewing the printout prior to printing. Actual printing then can be started directly from the print preview dialog, see Figure 2 3.

.. figure::  images/print_preview1.png
   :align:   center
   :target:  _images/print_preview1.png
   :name: print_preview1

   Print preview dialog
