Menu :guilabel:`Help`
^^^^^^^^^^^^^^^^^^^^^

This menu provides access to help on `PyAero <index.html>`_. 
Help is available via a link to the online `documentation <http://pyaero.readthedocs.io](http://pyaero.readthedocs.io>`_ or to a PDF version of it.

The :menuselection:`Help --> About PyAero` pops up awindow showing basic information on author and credits. 
Further it lists the versions of the main Python packages used in `PyAero <index.html>`_.
