Menu *Help*
^^^^^^^^^^^

The :guilabel:`Help` provides acces to help on `PyAero <index.html>`_. Help is available via a link to the online documentation or to a PDF file which should be shipped with the installation.

.. note::
   At the moment the PDF help does not exist.

The :menuselection:`Help --> About PyAero` pops up awindow showing basic information on author and credits. Further it lists the versions of the main modules used in `PyAero <index.html>`_.
