Menu ``View``
^^^^^^^^^^^

The :guilabel:`View` menu is used to set dedicated zoom levels or to toggle parameters of the view.

All submenus of the :menuselection:`View` menu  can be activated by respective shortcuts or by using the right mouse button inside the graphics view (see also :ref:`figure_main_screen`).

The :menuselection:`View --> Fit airfoil in view` does what it says. 
It fits the complete airfoil into the graphics view. 
This is exactly the same zoom and position after an airfoil has been loaded. 
The respective keyboard shortcut used is :kbd:`CTRL-f`.

The :menuselection:`View --> Fit all in view` does also what it says. 
It fits loaded airfoils or the complete mesh of the windtunnel into the graphics view. 
The respective keyboard shortcut used is :kbd:`CTRL-SHIFT-f`.

The :menuselection:`View --> Toggle background` can be used to toggle the background of the graphics view. The default background is a gradient from white (top) to dark grey (bottom). Toggling switches over to a solid white background. The respective keyboard shortcut used is :kbd:`CTRL-b`.

The :menuselection:`View --> Toggle message window` can be used to toggle the message window which is located below the the graphics view (see also :ref:`figure_main_screen`). Toggling hides the message window and after toggling once more brings it back again. The respective keyboard shortcut used is :kbd:`CTRL-m`.
