Menu :guilabel:`View`
^^^^^^^^^^^^^

This menu is used to set dedicated zoom levels or to toggle parameters of the view.

All submenus of the :menuselection:`View` menu can be activated by respective shortcuts or by 
using the right mouse button inside the graphics view (see also :ref:`figure_main_screen_new`).

Submenu :guilabel:`Fit airfoil in view`
"""""""""""""""""""""""""""""""""""""""

The :menuselection:`View --> Fit airfoil in view` does what it says. 

It fits the complete airfoil into the graphics view. 
This is exactly the same zoom and position which is used after an airfoil has been loaded. 
The keyboard shortcut for this submenu is :kbd:`CTRL-f`.

Submenu :guilabel:`Fit all in view`
"""""""""""""""""""""""""""""""""""""""

The :menuselection:`View --> Fit all in view` does also what it says. 
It fits loaded airfoils only (if no mesh exist yet) or the complete mesh of the windtunnel into the graphics view. 
The respective keyboard shortcut is :kbd:`CTRL-SHIFT-f`.

Submenu :guilabel:`Toggle background`
"""""""""""""""""""""""""""""""""""""

The :menuselection:`View --> Toggle background` can be used to toggle the background of the graphics view. 
The default background is a solid whit background.
Toggling switches over to a gradient filled background (white to dark grey, from top to bottom). 
The respective keyboard shortcut used is :kbd:`CTRL-b`.

Submenu :guilabel:`Toggle message window`
""""""""""""""""""""""""""""""""""""""""

The :menuselection:`View --> Toggle message window` can be used to toggle the message window 
which is located below the the graphics view (see also :ref:`figure_main_screen_new`).
Toggling hides the message window and after toggling once more it is brought back again. 
The respective keyboard shortcut used is :kbd:`CTRL-m`.

The message window is a so called floating window which can also be detached from the GUI.
It can be positioned anywhere on the screen and it can be reattched to the GUI again at any position ( top, bottom, left, right).
